---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-netpol
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
     - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-netpol
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-netpol
subjects:
- kind: ServiceAccount
  name: kube-netpol
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-netpol
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-netpol
  namespace: kube-system
  labels:
    tier: node
    app: kube-netpol
    k8s-app: kube-netpol
spec:
  selector:
    matchLabels:
      app: kube-netpol
  template:
    metadata:
      labels:
        tier: node
        app: kube-netpol
        k8s-app: kube-netpol
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: kube-netpol
      containers:
      - name: kube-netpol
        image: aojea/kube-netpol:v0.1.0
        args:
        - /bin/netpol
        - -v
        - "4"
        volumeMounts:
        - name: xtables-lock
          mountPath: /run/xtables.lock
          readOnly: false
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
---
